version: '3.7'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - .:/plugin

  shellcheck:
    image: koalaman/shellcheck:latest
    command: -x lib/bats-helper.bash hooks/environment hooks/post-checkout hooks/pre-checkout hooks/pre-exit configure.sh
    working_dir: /plugin
    volumes:
      - ".:/plugin"

  pytests:
    build:
      context: .
    command: python3 -m unittest
    working_dir: /plugin
    volumes:
      - ".:/plugin"