version: '3.7'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - .:/plugin

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'mikeknox/aws-paramstore-secrets']
    volumes:
      - ".:/plugin"

  shellcheck:
    image: koalaman/shellcheck:latest
    command: -x lib/shared.bash hooks/environment hooks/pre-exit
    working_dir: /plugin
    volumes:
      - ".:/plugin"

  pytests:
    build:
      context: .
    command: python3 -m unittest
    working_dir: /plugin
    volumes:
      - ".:/plugin"