steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.1.2:
        files:
          - hooks/**
          - lib/**
          - git-credential-parameterstore-secrets
          - *.sh

  - label: ":suitest: unit test"
    plugins:
      docker-compose#v3.3.0:
        run: tests
        config:
          - docker-compose.yml

  - label: ":suitest: python unit tests"
    plugins:
      docker-compose#v3.3.0:
        run: pytests
        config:
          - docker-compose.yml